WebApp/Models/Movies/Movie.cs
using System;
using System.Collections.Generic;

namespace WebApp.Models.Movies;

public partial class Movie
{
    public int MovieId { get; set; }

    public string? Title { get; set; }

    public int? Budget { get; set; }

    public string? Homepage { get; set; }

    public string? Overview { get; set; }

    public double? Popularity { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public long? Revenue { get; set; }

    public int? Runtime { get; set; }

    public string? MovieStatus { get; set; }

    public string? Tagline { get; set; }

    public double? VoteAverage { get; set; }

    public int? VoteCount { get; set; }
}

WebApp/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;
using WebApp.Models.Movies;

namespace WebApp.Controllers
{
    public class MovieController : Controller
    {
        private readonly MoviesDbContext _context;

        public MovieController(MoviesDbContext context)
        {
            _context = context;
        }

        // GET: Movie
        public IActionResult Index(int page = 1, int size = 10)
        {
            return View(PagingList.PagingListAsync<Movie>.Create(
                (p, s) => 
                    _context.Movies
                        .OrderBy(b => b.Title)
                        .Skip((p - 1) * s)
                        .Take(s)
                        .AsAsyncEnumerable(),
                _context.Movies.Count(),
                page,
                size));
        }

        
        
        // GET: Movie/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.MovieId == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movie/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movie/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Title, Overview, ReleaseDate, ProductionCompanyId")]
            MovieModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = _context.Movies.Add(new Movie()
                {
                    MovieId = _context.Movies.Max(m => m.MovieId) + 1,
                    Title = model.Title,
                    Overview = model.Overview,
                    ReleaseDate = model.ReleaseDate
                });
                _context.MovieCompanies.Add(new MovieCompany()
                {
                    CompanyId = model.CompanyId,
                    MovieId = entity.Entity.MovieId
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Movie/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movie/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MovieId,Title,Budget,Homepage,Overview,Popularity,ReleaseDate,Revenue,Runtime,MovieStatus,Tagline,VoteAverage,VoteCount")] Movie movie)
        {
            if (id != movie.MovieId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.MovieId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movie/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.MovieId == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            if (movie != null)
            {
                _context.Movies.Remove(movie);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.MovieId == id);
        }
    }
}

WebApp/Views/Movie/Create.cshtml
@model MovieModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Dodaj nowy film</h1>
<form asp-controller="Movie" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Title"></label>
        <span asp-validation-for="Title" class="text-danger"></span>
        <input class="form-control" asp-for="Title" />
    </div>

    <div class="form-group">
        <label asp-for="Overview"></label>
        <span asp-validation-for="Overview" class="text-danger"></span>
        <textarea class="form-control" asp-for="Overview"></textarea>
    </div>

    <div class="form-group">
        <label asp-for="ReleaseDate"></label>
        <span asp-validation-for="ReleaseDate" class="text-danger"></span>
        <input class="form-control" asp-for="ReleaseDate" type="date"/>
    </div>

    <div class="form-group">
        <label for="filter">Filtr producentów</label>
        <input class="form-control mb-3" type="text" name="filter" id="filter"/>
        <label asp-for="CompanyId"></label>
        <select class="form-control mb-3" asp-for="CompanyId" id="CompanyId"></select>
        <span asp-validation-for="CompanyId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button class="btn btn-primary" type="submit">Zapisz</button>
    </div>
</form>

@section Scripts {
<script>
    document.addEventListener("DOMContentLoaded", function() {
        let select = document.getElementById("CompanyId");
        let filter = document.getElementById("filter");
        filter.onchange = function (e) {
            if (filter.value.length == 0) {
                return;
            }
            fetch(`/api/contacts?filter=${filter.value}`)
                .then(response => {
                    if (response.ok) {
                        return response.json();
                    }
                    throw "No OK, actual status " + response.status;
                })
                .then(json => {
                    select.innerHTML = '';
                    for (let item of json) {
                        let option = document.createElement('option');
                        option.setAttribute('value', item.id);
                        option.innerText = item.title;
                        select.appendChild(option);
                    }
                })
                .catch(e => {
                    console.log('Nie można pobrać danych z API', e);
                });
        };
    });
</script>
}

WebApp/Views/Movie/Delete.cshtml
@model WebApp.Models.Movies.Movie

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Budget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Budget)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Homepage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Homepage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Overview)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Overview)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Popularity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Popularity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Revenue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Revenue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Runtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Runtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MovieStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MovieStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tagline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tagline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VoteAverage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VoteAverage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VoteCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VoteCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MovieId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/Views/Movie/Details.cshtml
@model WebApp.Models.Movies.Movie

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Budget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Budget)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Homepage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Homepage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Overview)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Overview)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Popularity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Popularity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Revenue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Revenue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Runtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Runtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MovieStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MovieStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tagline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tagline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VoteAverage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VoteAverage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VoteCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VoteCount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MovieId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Views/Movie/Edit.cshtml
@model WebApp.Models.Movies.Movie

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MovieId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget" class="control-label"></label>
                <input asp-for="Budget" class="form-control" />
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Homepage" class="control-label"></label>
                <input asp-for="Homepage" class="form-control" />
                <span asp-validation-for="Homepage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Overview" class="control-label"></label>
                <input asp-for="Overview" class="form-control" />
                <span asp-validation-for="Overview" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Popularity" class="control-label"></label>
                <input asp-for="Popularity" class="form-control" />
                <span asp-validation-for="Popularity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Revenue" class="control-label"></label>
                <input asp-for="Revenue" class="form-control" />
                <span asp-validation-for="Revenue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Runtime" class="control-label"></label>
                <input asp-for="Runtime" class="form-control" />
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieStatus" class="control-label"></label>
                <input asp-for="MovieStatus" class="form-control" />
                <span asp-validation-for="MovieStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tagline" class="control-label"></label>
                <input asp-for="Tagline" class="form-control" />
                <span asp-validation-for="Tagline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VoteAverage" class="control-label"></label>
                <input asp-for="VoteAverage" class="form-control" />
                <span asp-validation-for="VoteAverage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VoteCount" class="control-label"></label>
                <input asp-for="VoteCount" class="form-control" />
                <span asp-validation-for="VoteCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Views/Movie/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model WebApp.Models.PagingList.PagingListAsync<WebApp.Models.Movies.Movie>

@{
ViewData["Title"] = "Index";
Layout = "~/Views/Shared/_Layout.cshtml";
CancellationToken token = CancellationToken.None;
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Data.GetAsyncEnumerator(token).Current.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data.GetAsyncEnumerator(token).Current.Budget)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data.GetAsyncEnumerator(token).Current)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @await foreach (var item in Model.Data) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td class="text-end">
            @Html.DisplayFor(modelItem => item.Budget)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.Homepage))
            {
            <a href=@item.Homepage>Link to home page</a>
            }
            else
            {
            <p>Brak</p>
            }
        </td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.MovieId">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.MovieId">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.MovieId">Delete</a>
        </td>
    </tr>
    }
    </tbody>
</table>

<nav aria-label="Books page navigation">
    <ul class="pagination">
        @if (Model.IsPrevious)
        {
        <li class="page-item">
            <a class="page-link"
               asp-controller="Movies"
               asp-action="Index"
               asp-route-page="@(Model.Page - 1)"
               asp-route-size="@Model.Size">
                Poprzednia
            </a>
        </li>
        }
        else
        {
        <li class="page-item disabled">
            <a class="page-link">Poprzednia</a>
        </li>
        }
        <li class="page-item disabled">
            <a class="page-link" >@Model.Page</a>
        </li>
        @if (Model.IsNext)
        {
        <li class="page-item">
            <a class="page-link"
               asp-controller="Movies"
               asp-action="Index"
               asp-route-page="@(Model.Page + 1)"
               asp-route-size="@Model.Size">
                Następna
            </a>
        </li>
        }
        else
        {
        <li class="page-item disabled">
            <a class="page-link">Następna</a>
        </li>
        }
    </ul>
</nav>